version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/12factor
    user: "1000:1000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - laravel-network
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "4406:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
    env_file:
      - venv.env

networks:
  laravel-network:

volumes:
  dbdata:
